GET http://localhost:3000 HTTP/1.1

###
GET http://localhost:3000?email=emaila HTTP/1.1


###
POST http://localhost:3000 HTTP/1.1
content-Type: application/json

{
    "email": "emaila",
    "senha": "senha"
}
###
PUT http://localhost:3000?id=0 HTTP/1.1
content-Type: application/json

{
    "email": "email"
}
### 
DELETE http://localhost:3000?id=0 HTTP/1.1
content-Type: application/json
