GET http://localhost:3000 HTTP/1.1

###
GET http://localhost:3000?id=1 HTTP/1.1


###
POST http://localhost:3000 HTTP/1.1
content-Type: application/json

{
    "message": "hello"
}
###
PUT http://localhost:3000?id=1 HTTP/1.1
content-Type: application/json

{
    "message": "Mensagem mudada3"
}
### 
DELETE http://localhost:3000?id=2 HTTP/1.1
content-Type: application/json
